# Generated by Django 4.1.1 on 2023-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
