# Generated by Django 4.1.1 on 2023-01-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_alter_patient_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
