# Generated by Django 4.1.1 on 2023-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0005_alter_doctor_about_me_alter_doctor_education_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Profile_pic',
            field=models.ImageField(default='doctor.svg', null=True, upload_to=''),
        ),
    ]
