# Generated by Django 4.1.1 on 2023-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0006_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='dfjhjf@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='123235234'),
        ),
    ]
