# Generated by Django 4.1.1 on 2023-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0007_doctor_email_doctor_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
