# Generated by Django 4.1.1 on 2023-01-24 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Health', '0008_alter_doctor_email_alter_doctor_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_name', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Patient_name', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Date_of_scan', models.DateTimeField()),
                ('Date_of_recieved', models.DateTimeField()),
                ('Blood_pressure', models.IntegerField()),
                ('Sugar_level', models.IntegerField()),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameters_value', models.CharField(max_length=100)),
                ('Extra_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.medical_report')),
            ],
        ),
    ]
