# Generated by Django 4.1.1 on 2023-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0009_medical_report_extra_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Profile_pic',
            field=models.ImageField(default='doctor.png', null=True, upload_to=''),
        ),
    ]
