# Generated by Django 4.1.1 on 2023-01-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0010_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_values',
            name='Extra_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Health.medical_report'),
        ),
    ]
