# Generated by Django 4.1.1 on 2023-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0011_alter_extra_values_extra_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_report',
            name='description',
            field=models.TextField(default='None ', max_length=300),
        ),
        migrations.AddField(
            model_name='medical_report',
            name='doctor_prescription',
            field=models.TextField(default='None ', max_length=300),
        ),
    ]
